baseURL = 'https://moonrayspex.github.io'
languageCode = 'en-us'
title = 'Rachel Manderfeld, Portfolio'
theme = 'hugo-resume'


[params.main]
  enabled = true
  enableKatex = true
  metaKeywords = "gis"
  headerTitle = "Acorn Maps"
  copyright = "© 2021 Acorn Maps"
  name = "moonrayspex"
  img = "img/canoe.jpg"
  img_title = ""
  icon = "img/logo.png"
  quote = " Geographic Information Specialist, Applications Specialist"
  description= "Current GIS Applications specialist-in-training. My background in information science and experiences as a manager, inform my approach to the GIS field. I bring intentional communication, strong evaluative and critical thinking skills, and a coach-approach to leadership." 
  licenseUrl = ""




[params]
address = "Toronto, ON"
pronouns = "they / them"
email = "manderfeld.maps@gmail.com"
favicon = "/favicon.ico"
firstName = "Rachel Manderfeld,"
lastName = "MI"
profileImage = "img/canoe.jpg"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = true
showPublications = false
showQr = false
showSkills = true

[params.google]

[params.google.analytics]
trackerID = ""

[[params.handles]]
link = "https://www.linkedin.com/in/rachelmanderfeld/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/moonrayspex"
name = "GitHub"

[[params.handles]]
name = "Twitter"
link  = "https://twitter.com/AcornMaps"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"